### PR TITLE
Fix volume cap for protocol fee for buy orders

### PR DESCRIPTION
**Pull request by harisang**
Follow up PR on #67 that takes care of volume cap for buy orders.

### CODE REVIEW

**Comment by fhenneke** [comment]
I would prefer if the removal of the case for 100% volume cap were done later. Resyncing data for last week might not be possible with the new code.

**Comment by harisang** [comment]
> I would prefer if the removal of the case for 100% volume cap were done later. Resyncing data for last week might not be possible with the new code.

Can you elaborate a bit? Where exactly would the resyncing fail?

**Comment by fhenneke** [comment]
> Can you elaborate a bit? Where exactly would the resyncing fail?

My mistake, it should be fine.

**Review by fhenneke — APPROVED** [review]
Ran tests locally and they passed.

**Pull request merged**
